### ISSUE TITLE
Clarification about usages as library

### ISSUE THREAD

**Issue by cmkhaledsaifullah** [SLP-team/SLP-Core#12]
Hi,
First of all thank you very much for sharing the code especially the examples portion. I like to compare your approach with mine for method completion and i was looking at the examples as they are well documented. I find CharacterWordHybrid class as an useful code. I need some clarification:
1. You are returning the probability value of each token in the test corpus, right? if so, then i need to see the top 10 token based on probability for each token, how can i get that. what i understand is in wordProbs, you are storing only the current token's probability.

2. Your training process worked for all tokens but if i like to filter some, is it possible? 

3. how can i merge the lstm and n gram model?

Thansk for your time

**Comment by VHellendoorn** [comment]
Hi,

Thanks for reaching out. I'm glad you like the `CharacterWordHybrid` example, although I should point out that it is currently not very useful as an actual hybrid model because it just runs two separate models. In due course I am hoping to make it a more proper hybrid. As for your questions:

1. The value returned is not quite a probability, but rather the corresponding entropy for each token, which can be converted into a probability with `2^(-entropy)`. To get top-10 scores like you are asking, please look into using `ModelRunner`s `completFile` (and similar) methods: these are different from `modelFile` and `predictFile` in that they return completions for each token on each line (so a `List` of `List`s of `Completion` objects). Each `Completion` object contains a sorted list of suggestions for that token given its context and each suggestion stores both its index in the vocabulary and its probability (a proper probability this time, not an entropy). Increase the `GLOBAL_PREDICTION_CUTOFF` in `ModelRunner` for more suggestions (default is 10)
2. It sounds like you want to skip some tokens in the training and testing data? The easiest way is to write a `Lexer` that wraps the (e.g.) `JavaLexer` and filters its outputs. For instance, if you want to drop all punctuation symbols, just invoke the `JavaLexer` first, then apply a `filter` to its token stream in which you check if any of its tokens are punctuation (e.g. using a regex) and return this filtered stream. For examples on how to wrap `Lexer`s, see some of the `util` `Lexer`s that I provided, like `SkipEmptyLexer` (which drops empty string tokens). If you mean instead to filter in the output, it's best to just do this after the fact by looping over the results (e.g. the `Completion`s), translating all the indices back to words using the `Vocabulary` and applying whatever rule/regex you'd like to get the results for tokens you are interested in.
3. This can only really be done after the fact at present. Use your favorite tool to get probabilities from an LSTM (make sure they are proper probabilities) and store them in a file aligned with tokens. Use SLP-Core to write a similar file, either with your own code or using the `Writer.writeEntropies` functionality (which is a bit iffy right now) and merge them in whatever way you prefer. I'd recommend not using the `LSTM` in the replication folder; Tensorflow moves fast and that code is certainly not up-to-date or fast or particularly useful.

Hope this helps!

**Comment by cmkhaledsaifullah** [comment]
Thank you very much for your help. I am looking forward the solution you directed. Your gracious contribution will be highlighted in my study. Beside, If I can make enough changes and if you think the changes are worthy enough, you can pull those as an example with the current system.

**Comment by VHellendoorn** [comment]
Great, I'll close this for now. P.S.: if you are pulling from master, please note that I just pushed a fix for a serious bug in the `CacheModel` that has been there for about a month. Please pull the latest version for good comparison; otherwise claim SLP-Core may perform way too well
