### ISSUE TITLE
How to retrieve probability values

### ISSUE THREAD

**Issue by antonio-mastropaolo** [SLP-team/SLP-Core#16]
Hi everyone, 

I was wondering if there is a way to extract the probability value associated with a predicted token when we compute the MRR metric. In other words, let's consider the following prediction:
static1.000000	clockid_t0.000000

I want to get for the 'static' token(where the MRR is 1) the probability or the confidence level --so to speak-- of the model.
Any ideas?

Thank you all in advance :)

**Comment by VHellendoorn** [comment]
Hi!

It sounds like you're looking for the _entropy_ associated with each token, which is itself just a simple transformation of probability. That's easy enough if you've already got the predict mode set up, as you seem to. Assuming you're doing this from the command-line (where you use the `--verbose` option to write to file), you'd simply change the run mode from `train-predict` to `train-test` (or both without `train-` if applicable).

If you're using the programmatic interface, the change is similar; once the model is trained, just call the `ModelRunner`'s `modelX` family of methods instead of the `predictX` ones.

Hope this helps!

-Vincent
