### ISSUE TITLE
GigaCounter opens a lot of threads for files skipped by the lexer

### ISSUE THREAD

**Issue by dgopstein** [SLP-team/SLP-Core#5]
When I try to model/learn a directory with a lot of non-source files, my JVM crashes from too many open threads. This is happening for me while processing C files in `gecko-dev/testing` which has 10 c files and ~75k non-c files on a 12-threaded cpu. I think the cause of this issue is shared among several modules, and can likely be solved at any/all of them:

* The `LexerRunner` is tasked with determining which files should be modeled (using a regex over file names). However, since the Lexer is only concerned with content inside of files the way it signals that a file ought not be modeled, is by returning an empty stream of tokens.
* At a higher level, in the `ModelRunner` must send every file to the `LexerRunner` to be lexed, then take whatever the output of that is, and send it along to the model to be modeled. Since it has no notion of whether or not the file it's evaluating is relevant, many empty streams are passed along.
* Each model, then, sends a (in my case) a likely empty stream to the (in my case) `GigaCounter` which submits the counting task to its `ForkJoinPool`.
* Since the `Lexer` is doing effectively no work, the number of threads appended to the `ForkJoinPool` grow much more quickly than the `Counter` can clear the queue.

My intuition is to simply filter out un-interesting files earlier on in the pipeline, before calling [`learnFile`](https://github.com/SLP-team/SLP-Core/blob/master/src/main/java/slp/core/modeling/ModelRunner.java#L113), e.g.:

`.filter(f -> f.getName().matches(lexerRunner.getRegex()))`

However that also has other implications:
* `model` would no longer return `Pair`s for skipped files. Would that have adverse effects?
* If file-type filtering is no longer done in the `LexerRunner` should that regex be moved somewhere else instead?
* This fix only works because it hides many irrelevant and quickly-lexed files from the `Lexer` this fix would not help in the event that you had 70k empty C files in a directory
  * To fix the above issue would likely require task-queuing outside the `ForkJoinQueue` so that threads are not created for files before they're ready to be processed

**Comment by VHellendoorn** [comment]
That's an interesting issue; I hadn't run into it myself. For the most part, I think it makes sense to add this filter in `ModelRunner`'s learn/forget/model/predict-File methods. There is no need for it to return `Pair`s for non-source files anyways, so that will be taken care of as well. I want to leave the check inside the `LexerRunner` as well though, since other accesses to that method should still have well-defined behavior.

That leaves the second issue you point out, which should be fixed inside `GigaCounter`. I'm adding a live-lock on the pool size if it grows too large for now. It is a bit odd that this would happen at all though, since the code is supposed to wait for a thread thread to become available in `getNextAvailable`, which loops until a cpu is freed. That should imply that there are never more than (in your case) 6 threads used here. Perhaps it's in the `resolve` part that this goes wrong?

**Comment by dgopstein** [comment]
Another alternative, and (not that I really enjoy long type signatures, but) perhaps the philosophically correct one, would be to change the type for `LexerRunner`'s `.lex(File)` method to `Optional<Stream<Stream<String>>>`. This would just take the current type wraps it in an `Optional` to signify whether the file was lexed or not. The value of this approach is that it allows the result of `lex()` to be `flatMap`'d over without having to spread the logic for "should this file be lexed or not" outside of the `LexerRunner`

Oh, interesting, I hadn't even noticed the `resolve` method. Is that method necessary for a counting thread to die?

**Comment by VHellendoorn** [comment]
I certainly agree with the Optional part, but the length of the resulting type signatures puts me off, especially since the result of lexing is itself wrapped in collections sometimes. A simple, if less satisfying solution might be to return `null` on non-matching extensions and `filter` those out instead. Or wrap the outcome in some LexingResult-type class. For now, I'll stick with the empty stream and avoid returning one as much as possible.

The `resolve` method is a story in itself. I needed a `Counter` that could handle very large corpora, but the `Trie` updates got too costly when it grew larger. I figured I could settle for a forest of `Trie`s instead (_i.e._ the `VirtualCounter`), but I didn't account for Java's gc. As it turns out, even "parked" `Trie`s that are   not being updated are still subject to traversal by the gc, which is far too slow due to the many pointers inside a `Trie`. So the `GigaCounter` builds a forest of `Trie`s that get serialized into byte arrays when they reach a certain size until counting is complete, at which point they are resolved (unpacked and assimilated) into a `VirtualCounter`. Hopefully with Java 10's updates to gc, this won't be necessary anymore.

**Comment by VHellendoorn** [comment]
Resolved in #6
